#!/bin/bash -e
set -e

APP="$1"; IMAGE="dokku/$APP"
echo "-----> Injecting ffmpeg ..."

FFMPEG_PATH="/usr/local/bin/ffmpeg"

COMMAND=$(cat <<EOF
export DEBIAN_FRONTEND=noninteractive
if [ ! -f $FFMPEG_PATH ]; then
    wget --quiet -O $FFMPEG_PATH https://www.dropbox.com/s/n7k22xr92lalioy/ffmpeg
    chmod +x $FFMPEG_PATH
    echo "       Injected ffmpeg"
fi
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)
ID=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
#enable logs
docker attach $ID
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null
